/**
 * CSS property order used to sort utilities with the same variants, so shorthands come
 * before longhands (`p-4 px-2` behaves as expected). Matches Tailwind CSS v4 (see NOTICE.md).
 */
export const PROPERTY_ORDER: readonly string[] = [
  "container-type", "pointer-events", "visibility", "position", "inset", "inset-inline",
  "inset-block", "inset-inline-start", "inset-inline-end", "inset-block-start", "inset-block-end", "top",
  "right", "bottom", "left", "isolation", "z-index", "order",
  "grid-column", "grid-column-start", "grid-column-end", "grid-row", "grid-row-start", "grid-row-end",
  "float", "clear", "--spk-u-container-component", "margin", "margin-inline", "margin-block",
  "margin-inline-start", "margin-inline-end", "margin-block-start", "margin-block-end", "margin-top", "margin-right",
  "margin-bottom", "margin-left", "box-sizing", "display", "field-sizing", "aspect-ratio",
  "height", "max-height", "min-height", "width", "max-width", "min-width",
  "flex", "flex-shrink", "flex-grow", "flex-basis", "table-layout", "caption-side",
  "border-collapse", "border-spacing", "transform-origin", "translate", "--spk-u-translate-x", "--spk-u-translate-y",
  "--spk-u-translate-z", "scale", "--spk-u-scale-x", "--spk-u-scale-y", "--spk-u-scale-z", "rotate",
  "--spk-u-rotate-x", "--spk-u-rotate-y", "--spk-u-rotate-z", "--spk-u-skew-x", "--spk-u-skew-y", "transform",
  "zoom", "animation", "cursor", "touch-action", "--spk-u-pan-x", "--spk-u-pan-y",
  "--spk-u-pinch-zoom", "resize", "scroll-snap-type", "--spk-u-scroll-snap-strictness", "scroll-snap-align", "scroll-snap-stop",
  "scroll-margin", "scroll-margin-inline", "scroll-margin-block", "scroll-margin-inline-start", "scroll-margin-inline-end", "scroll-margin-block-start",
  "scroll-margin-block-end", "scroll-margin-top", "scroll-margin-right", "scroll-margin-bottom", "scroll-margin-left", "scroll-padding",
  "scroll-padding-inline", "scroll-padding-block", "scroll-padding-inline-start", "scroll-padding-inline-end", "scroll-padding-block-start", "scroll-padding-block-end",
  "scroll-padding-top", "scroll-padding-right", "scroll-padding-bottom", "scroll-padding-left", "scrollbar-width", "scrollbar-color",
  "scrollbar-gutter", "list-style-position", "list-style-type", "list-style-image", "appearance", "columns",
  "break-before", "break-inside", "break-after", "grid-auto-columns", "grid-auto-flow", "grid-auto-rows",
  "grid-template-columns", "grid-template-rows", "flex-direction", "flex-wrap", "place-content", "place-items",
  "align-content", "align-items", "justify-content", "justify-items", "gap", "column-gap",
  "row-gap", "--spk-u-space-x-reverse", "--spk-u-space-y-reverse", "divide-x-width", "divide-y-width", "--spk-u-divide-y-reverse",
  "divide-style", "divide-color", "place-self", "align-self", "justify-self", "overflow",
  "overflow-x", "overflow-y", "overscroll-behavior", "overscroll-behavior-x", "overscroll-behavior-y", "scroll-behavior",
  "border-radius", "border-start-radius", "border-end-radius", "border-top-radius", "border-right-radius", "border-bottom-radius",
  "border-left-radius", "border-start-start-radius", "border-start-end-radius", "border-end-end-radius", "border-end-start-radius", "border-top-left-radius",
  "border-top-right-radius", "border-bottom-right-radius", "border-bottom-left-radius", "border-width", "border-inline-width", "border-block-width",
  "border-inline-start-width", "border-inline-end-width", "border-block-start-width", "border-block-end-width", "border-top-width", "border-right-width",
  "border-bottom-width", "border-left-width", "border-style", "border-inline-style", "border-block-style", "border-inline-start-style",
  "border-inline-end-style", "border-block-start-style", "border-block-end-style", "border-top-style", "border-right-style", "border-bottom-style",
  "border-left-style", "border-color", "border-inline-color", "border-block-color", "border-inline-start-color", "border-inline-end-color",
  "border-block-start-color", "border-block-end-color", "border-top-color", "border-right-color", "border-bottom-color", "border-left-color",
  "background-color", "background-image", "--spk-u-gradient-position", "--spk-u-gradient-stops", "--spk-u-gradient-via-stops", "--spk-u-gradient-from",
  "--spk-u-gradient-from-position", "--spk-u-gradient-via", "--spk-u-gradient-via-position", "--spk-u-gradient-to", "--spk-u-gradient-to-position", "mask-image",
  "--spk-u-mask-top", "--spk-u-mask-top-from-color", "--spk-u-mask-top-from-position", "--spk-u-mask-top-to-color", "--spk-u-mask-top-to-position", "--spk-u-mask-right",
  "--spk-u-mask-right-from-color", "--spk-u-mask-right-from-position", "--spk-u-mask-right-to-color", "--spk-u-mask-right-to-position", "--spk-u-mask-bottom", "--spk-u-mask-bottom-from-color",
  "--spk-u-mask-bottom-from-position", "--spk-u-mask-bottom-to-color", "--spk-u-mask-bottom-to-position", "--spk-u-mask-left", "--spk-u-mask-left-from-color", "--spk-u-mask-left-from-position",
  "--spk-u-mask-left-to-color", "--spk-u-mask-left-to-position", "--spk-u-mask-linear", "--spk-u-mask-linear-position", "--spk-u-mask-linear-from-color", "--spk-u-mask-linear-from-position",
  "--spk-u-mask-linear-to-color", "--spk-u-mask-linear-to-position", "--spk-u-mask-radial", "--spk-u-mask-radial-shape", "--spk-u-mask-radial-size", "--spk-u-mask-radial-position",
  "--spk-u-mask-radial-from-color", "--spk-u-mask-radial-from-position", "--spk-u-mask-radial-to-color", "--spk-u-mask-radial-to-position", "--spk-u-mask-conic", "--spk-u-mask-conic-position",
  "--spk-u-mask-conic-from-color", "--spk-u-mask-conic-from-position", "--spk-u-mask-conic-to-color", "--spk-u-mask-conic-to-position", "box-decoration-break", "background-size",
  "background-attachment", "background-clip", "background-position", "background-repeat", "background-origin", "mask-composite",
  "mask-mode", "mask-type", "mask-size", "mask-clip", "mask-position", "mask-repeat",
  "mask-origin", "fill", "stroke", "stroke-width", "object-fit", "object-position",
  "padding", "padding-inline", "padding-block", "padding-inline-start", "padding-inline-end", "padding-block-start",
  "padding-block-end", "padding-top", "padding-right", "padding-bottom", "padding-left", "text-align",
  "text-indent", "vertical-align", "font-family", "font-feature-settings", "font-size", "line-height",
  "font-weight", "letter-spacing", "text-wrap", "overflow-wrap", "word-break", "text-overflow",
  "hyphens", "white-space", "tab-size", "color", "text-transform", "font-style",
  "font-stretch", "font-variant-numeric", "text-decoration-line", "text-decoration-color", "text-decoration-style", "text-decoration-thickness",
  "text-underline-offset", "-webkit-font-smoothing", "placeholder-color", "caret-color", "accent-color", "color-scheme",
  "opacity", "background-blend-mode", "mix-blend-mode", "box-shadow", "--spk-u-shadow", "--spk-u-shadow-color",
  "--spk-u-ring-shadow", "--spk-u-ring-color", "--spk-u-inset-shadow", "--spk-u-inset-shadow-color", "--spk-u-inset-ring-shadow", "--spk-u-inset-ring-color",
  "--spk-u-ring-offset-width", "--spk-u-ring-offset-color", "outline", "outline-width", "outline-offset", "outline-color",
  "--spk-u-blur", "--spk-u-brightness", "--spk-u-contrast", "--spk-u-drop-shadow", "--spk-u-grayscale", "--spk-u-hue-rotate",
  "--spk-u-invert", "--spk-u-saturate", "--spk-u-sepia", "filter", "--spk-u-backdrop-blur", "--spk-u-backdrop-brightness",
  "--spk-u-backdrop-contrast", "--spk-u-backdrop-grayscale", "--spk-u-backdrop-hue-rotate", "--spk-u-backdrop-invert", "--spk-u-backdrop-opacity", "--spk-u-backdrop-saturate",
  "--spk-u-backdrop-sepia", "backdrop-filter", "transition-property", "transition-behavior", "transition-delay", "transition-duration",
  "transition-timing-function", "will-change", "contain", "content", "forced-color-adjust",
];
